function moon() {
    document.getElementById("template").src = "Weird_template.png";
    document.getElementById("img_data").src = "moon_onclick.jpeg";
    document.getElementById("data").innerHTML = "Moons – also known as natural satellites – orbit planets and asteroids in our solar system. <br>Earth has one moon, and there are more than 200 moons in our solar system. <br>Most of the major planets – all except Mercury and Venus – have moons. ‘There used to be a number of theories about how the Moon was made and it was one of the aims of the Apollo program to figure out how we got to have our Moon.'Prior to the Apollo mission research there were three theories about how the Moon formed. Capture theory suggests that the Moon was a wandering body (like an asteroid)<br> that formed elsewhere in the solar system and was captured by Earth's gravity as it passed nearby. In contrast, accretion theory suggested that the Moon was created along with Earth at its formation. Finally, according to the fission scenario, Earth had been spinning so fast that some material broke away and began to orbit the planet. What is most widely accepted today is the giant-impact theory. It proposes that the Moon formed during a collision between the Earth and another small planet, about the size of Mars. The debris from this impact collected in an orbit around Earth to form the Moon. Earth and the Moon have some remarkable chemical and isotopic similarities, suggesting that they have a linked history. 'If the Moon had been created elsewhere and was captured by the Earth's gravity we would expect its composition to be very different from the Earth's. 'If the Moon was created at the same time, or broke off the Earth, then we would expect the type and proportion of minerals on the Moon to be the same as on Earth. But they are slightly different. 'The minerals on the Moon contain less water than similar terrestrial rocks. The Moon is rich in material that forms quickly at a high temperature. However, what is really special on the Moon, that we can't ever replicate on Earth, is that the Moon is geologically rather dead. By looking at the Moon we can tell a lot about what the Earth was like four billion years ago.";

}

function time_travel() {
    document.getElementById("template").src = "Weird_template.png";
    document.getElementById("img_data").src = "time travel.jpg";
    document.getElementById("data").innerHTML = "Time travel is the concept of movement between certain points in time, analogous to movement between different points in space by an object or a person, typically with the use of a hypothetical device known as a time machine.We all travel in time! We travel one year in time between birthdays, for example. And we are all traveling in time at approximately the same speed: 1 second per second. NASA's space telescopes also give us a way to look back in time. Telescopes help us see stars and galaxies that are very far away. It takes a long time for the light from faraway galaxies to reach us. So, when we look into the sky with a telescope, we are seeing what those stars and galaxies looked like a very long time ago.However, when we think of the phrase time travel, we are usually thinking of traveling faster than 1 second per second. That kind of time travel sounds like something you'd only see in movies or science fiction books. Could it be real? Science says yes! More than 100 years ago, a famous scientist named Albert Einstein came up with an idea about how time works. He called it relativity. Well, according to this theory, the faster you travel, the slower you experience time. For example, there was an experiment that used two clocks set to the exact same time. One clock stayed on Earth, while the other flew in an airplane (going in the same direction Earth rotates). After the airplane flew around the world, scientists compared the two clocks. The clock on the fast-moving airplane was slightly behind the clock on the ground. So, the clock on the airplane was traveling slightly slower in time than 1 second per second. Yes, time travel is indeed a real thing. But it's not quite what you've probably seen in the movies. Under certain conditions, it is possible to experience time passing at a different rate than 1 second per second. And there are important reasons why we need to understand this real-world form of time travel.";
}

function hollow_theory() {
    document.getElementById("template").src = "Weird_template.png";
    document.getElementById("img_data").src = "hollow_earth.jpg";
    document.getElementById("data").innerHTML = "There's a conspiracy theory that says the Earth is hollow and that there might even be a whole other civilization of advanced beings living in it. The theory is rooted back in the 17th century when Edmond Halley—who has a comet named after him—proposed that the Earth must be hollow because of changing magnetism.  The Hollow Earth is a concept proposing that the planet Earth is entirely hollow or contains a substantial interior space. The crux of the hollow earth theory is that the earth is a shell with walls about 800 miles thick. In the polar regions there are holes 1400 miles across, with edges that curve smoothly from the outside of the shell around to the inside. A sea or surface traveller could proceed over an edge of the hole, like an ant crawling over the lip of a coffee mug from the outside to the inside, and not be aware that he was actually entering the interior of the earth. The hollow earth theory actually seems to have been originated in the early 1800s by John Symmes, an earnest American who devoted the greater part of his later life to convincing the world that the earth was formed by a series of concentric shells. In 2014, scientists found  a reservoir of water three times the volume of all the oceans  deep within Earth. The water, however, isn't just sloshing around within Earth—it's inside ringwoodite, a rock that's 435 miles deep beneath Earth's surface. For some, this bolstered the theory that Earth was hollow, since the water was solidified in rock form. None of the claims of Hollow Earth proponents have been substantiated, however. Those still holding to the belief in the twenty-first century are part of a long history of people who believe human life exists beneath the surface of the Earth. An early hollow Earth theory was proposed by the English astronomer Edmund Halley (of comet fame) in 1692. He suggested that the Earth is a shell 500 miles thick with two inner shells and a solid inner sphere, all capable of sustaining life.";

}

function cosmic_ghost() {
    document.getElementById("template").src = "Weird_template.png";
    document.getElementById("img_data").src = "cosmic_ghost.jpg";
    document.getElementById("data").innerHTML = "Neutrinos are the ghosts of the universe. They pass through all matter and travel at near the speed of light. And some begin with a star's violent death. The ghosts of the universe.They pass through you, me, and, in fact, all matter. They travel at near the speed of light. They morph into different forms. And some begin with the violent death of a star. The recently proposed infrared modification of gravity through the introduction of a ghost scalar field results in a number of interesting cosmological and phenomenological implications. In this paper, we derive the exact cosmological solutions for a number of scenarios where at late stages, the ghost behaves like dark matter, or dark energy. The full solutions give valuable information about the non-linear regime beyond the asymptotic first order analysis presented in the literature. The generic feature is that these ghost cosmologies give rise to smooth transitions between radiation dominated phases (or more general power-law expansions) at early epochs and ghost dark matter resp. ghost dark energy dominated late epochs. The current age of our universe places us right at the non-linear transition phase. By studying the evolution backwards in time, we find that the dominance of the ghost over ordinary baryonic matter and radiative contributions persists back to the earliest times such that the Friedmann-Robertson-Walker geometry is dictated to a good approximation by the ghost alone. We also find that the Jeans instability occurs in the ghost dark energy scenario at late times, while it is absent in the ghost dark matter scenario.";
}

function bermuda_triangle() {
    document.getElementById("template").src = "Weird_template.png";
    document.getElementById("img_data").src = "bermuda triangle.jpg";
    document.getElementById("data").innerHTML = "The Bermuda Triangle is a region in the western part of the North Atlantic Ocean in which ships, planes, and people are alleged to have mysteriously vanished. For decades, the Atlantic Ocean’s fabled Bermuda Triangle has captured the human imagination with unexplained disappearances of ships, planes, and people. Some speculate that unknown and mysterious forces account for the unexplained disappearances, such as extraterrestrials capturing humans for study; the influence of the lost continent of Atlantis; vortices that suck objects into other dimensions; and other whimsical ideas. Environmental considerations could explain many, if not most, of the disappearances.  The majority of Atlantic tropical storms and hurricanes pass through the Bermuda Triangle, and in the days prior to improved weather forecasting, these dangerous storms claimed many ships.  Also, the Gulf Stream can cause rapid, sometimes violent, changes in weather.  Additionally, the large number of islands in the Caribbean Sea creates many areas of shallow water that can be treacherous to ship navigation. And there is some evidence to suggest that the Bermuda Triangle is a place where a “magnetic” compass sometimes points towards “true” north, as opposed to “magnetic” north. The ocean has always been a mysterious place to humans, and when foul weather or poor navigation is involved, it can be a very deadly place.  This is true all over the world.  There is no evidence that mysterious disappearances occur with any greater frequency in the Bermuda Triangle than in any other large, well-travelled area of the ocean. ";
}

function allien_existence() {
    document.getElementById("template").src = "Weird_template.png";
    document.getElementById("img_data").src = "alian_weird.jpg";
    document.getElementById("data").innerHTML = "Alien dreams have always been powered by the desire for human importance in a vast, forgetful cosmos: We want to be seen so we know we exist. What’s unusual about the alien fantasy is that, unlike religion, nationalism, or conspiracy theory, it doesn’t place humans at the center of a grand story. Is mankind alone in the universe? Or are there somewhere other intelligent beings looking up into their night sky from very different worlds and asking the same kind of question? Are there civilizations more advanced than ours, civilizations that have achieved interstellar communication and have established a network of linked societies throughout our galaxy? Such questions, bearing on the deepest problems of the nature and destiny of mankind, were long the exclusive province of theology and speculative fiction. In our present ignorance of how common extraterrestrial life may actually be, any attempt to estimate the number of technical civilizations in our galaxy is necessarily unreliable. Do aliens exist? This is a really interesting question and one that NASA has been trying to understand, explore, and figure out for a long time. We have not yet discovered life on any other planet, and we have not seen any scientifically supported evidence for extraterrestrial life. There are icy moons in the outer solar system like Saturn’s moon Enceladus and Jupiter’s moon Europa that look like they may have subsurface oceans that could be habitable. And that's just what's in our solar system. The more exoplanets we find around other stars, the more we learn about how many different environments could exist for life. We can't yet say for sure whether or not aliens exist. To quote Carl Sagan: “The universe is a pretty big place. If it's just us, it seems like an awful waste of space.” So, NASA will keep looking. ";
}

function human_love() {
    document.getElementById("template").src = "Weird_template.png";
    document.getElementById("img_data").src = "human love.jpg";
    document.getElementById("data").innerHTML = "Love. From flurries of excitement, joy and infatuation, to crippling self-consciousness, deep attachment and even all-consuming fear, it’s a potent cocktail of emotions. So powerful, in fact, it has a profound impact on your body.Love, can also have major consequences on your brain too – think about when your mind has wandered away from work or conversations to ponder about a loved one. Most of us have heard of oxytocin as the “cuddle hormone” or “love hormone” as it’s associated with social connection and released during sex. Yet there isn’t just one hormone, and you cannot simply spritz yourself in oxytocin and find love. Instead, there is likely a cocktail of hormones interacting in a specific way in humans that lead us to love. “There are three areas in the brain that act as a magic trilogy, interacting with three key hormones: dopamine, oxytocin and vasopressin. All organisms have these hormones, and they have different functions, but it is the parts of our brain that they interact with that make them important. To simplify, these three brain regions are:<br> •	Ventral tegmental area (VTA), which releases dopamine.<br> •	Nucleus accumbens (NA), containing many oxytocin receptors.<br> •	Ventral pallidum (VP), containing many vasopressin receptors.<br> These are all interlinked reward systems, which fire up in response to drugs and the hormones associated with love. Anecdotally, love is a matter of the heart. However, the main organ affected by love is actually the brain. Butterflies in your stomach. That giddy feeling you get when the person you like is nearby. Excitement to be around them again. All of these feelings will be familiar to people who have fallen in love. Where is love “located” in the brain, and what does it do to our minds and bodies, according to science. There are a number of brain regions that are more active when people look at their beloved than when they look at other people.<br> ";
}