function Artificial() {
    document.getElementById("information").innerHTML = "Artificial Intelligence";
    document.getElementById("data").innerHTML = "Artificial intelligence (AI), the ability of a digital computer or computer-controlled robot to perform tasks commonly associated with intelligent beings. Here the machine is thought how to think or react according to the conditions. As it is the superset of machine learning and data science. The term AI is frequently applied to the project of developing systems endowed with the intellectual processes characteristic of humans, such as the ability to reason, discover meaning, generalize, or learn from past experience. Since the development of the digital computer in the 1940s, it has been demonstrated that computers can be programmed to carry out very complex tasks like thinking, visualizing, processing over an data and many more thing. Still, despite continuing advances in computer processing speed and memory capacity, there are as yet no programs that can match human flexibility over wider domains or in tasks requiring much everyday knowledge. Although a critical thinking has been developed in computers to match humans intellectual. AI research follows two distinct, and to some extent competing, methods, the symbolic top-down approach, and the connectionist bottom-up approach.<br><br> The current suggested languages for AI due to their huge libraries are:-<br>1.Phyton <br> 2.LISP <br> 3.Javascript<br><br> Here are platforms for learning and executing AI logic:-<br>1.Google cloud AI<br>2.Microsoft Azure AI <br>3.H20.ai.";

}

function Machine() {
    document.getElementById("information").innerHTML = "Machine Learning";
    document.getElementById("data").innerHTML = "Machine learning (ML) is a type of artificial intelligence (AI) that is it is the subset of Artificial Intelligence(AI) that allows software applications to become more accurate at predicting outcomes without being explicitly programmed to do so. Machine learning algorithms use historical data as input to predict new output values. here the machine has been made capable to study the historic data and make the decision depending on the conditions learning from the data. Machine learning is important because it gives enterprises a view of trends in customer behavior and business operational patterns, as well as supports the development of new products. Many of today's leading companies, such as Facebook, Google and Uber, make machine learning a central part of their operations. Machine learning has become a significant competitive differentiator for many companies. There are different type of machine learning like supervised learning, unsupervised learning, semi-supervised learning and reinforcement learning. The type of algorithm data scientists choose to use depends on what type of data they want to predict.For.ex. the self driven car of tesla has used the dojo the neural network of ML.<br><br>Here are the tool that are used for ML learning and development:-<br>1.Scikit Learn<br>2.tensorflow<br>3.Theano<br>4.Caffe<br>5.MxNet<br>6. Azure ML studio<br>This are the platform and the libraries that will help you to learn and develop many new thing in this technology.";

}

function Data_Science() {
    document.getElementById("information").innerHTML = "Data Science ";
    document.getElementById("data").innerHTML = "Data science is the domain of study that deals with vast volumes of data using modern tools and techniques to find unseen patterns, derive meaningful information, and make business decisions. Data science uses complex machine learning algorithms to build predictive models.  The data used for analysis can come from many different sources and presented in various formats.Likely we can say that data science is the subset of AI and ML.Data science’s lifecycle consists of five distinct stages, each with its own tasks:<br>1.Capture<br>2.Maintain<br>3.Process<br>4.Analyze<br>5.Communicate<br><br>Here to maintain such a huge data we have a Data Scientist,Data Analyst,Data Engineer.<br>The skills required for the above degignation are:-<br>1. Programming skills (SAS, R, Python)<br>2. storytelling and data visualization<br>3. statistical and mathematical skills<br>4. knowledge of Hadoop, SQL, and Machine Learning.<br><br>The tools availabe for learning and development are:-<br>1.Data Analysis: SAS, Jupyter, R Studio, MATLAB, Excel, RapidMiner<br>2. Data Warehousing: Informatica/ Talend, AWS Redshift<br>3. Data Visualization: Jupyter, Tableau, Cognos, RAW<br>";

}